<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26791" started-at="2022-09-01T17:06:56 IST" finished-at="2022-09-01T17:07:23 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26791" started-at="2022-09-01T17:06:56 IST" finished-at="2022-09-01T17:07:23 IST">
      <class name="com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol@1f57539]" name="setUp" is-config="true" duration-ms="5654" started-at="2022-09-01T17:06:56 IST" finished-at="2022-09-01T17:07:02 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="sampleAcknowledgementARNumbersforaProtocol()[pri:0, instance:com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol@1f57539]" name="sampleAcknowledgementARNumbersforaProtocol" duration-ms="17878" started-at="2022-09-01T17:07:02 IST" finished-at="2022-09-01T17:07:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol.methodTogetARNumbersSampleAcknowledgement(SampleAcknowledgementARNumbersforaProtocol.java:215)
at com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol.sampleAcknowledgementARNumbersforaProtocol(SampleAcknowledgementARNumbersforaProtocol.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAcknowledgementARNumbersforaProtocol -->
        <test-method status="PASS" signature="testIT(org.testng.ITestResult)[pri:0, instance:com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol@1f57539]" name="testIT" is-config="true" duration-ms="291" started-at="2022-09-01T17:07:20 IST" finished-at="2022-09-01T17:07:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sampleAcknowledgementARNumbersforaProtocol status=FAILURE method=SampleAcknowledgementARNumbersforaProtocol.sampleAcknowledgementARNumbersforaProtocol()[pri:0, instance:com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol@1f57539] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIT -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol@1f57539]" name="tearDown" is-config="true" duration-ms="2891" started-at="2022-09-01T17:07:20 IST" finished-at="2022-09-01T17:07:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.pss.lims.StabilityManagement.ForwardFlow.SampleAcknowledgementARNumbersforaProtocol -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
